# Generated by Django 4.1 on 2022-09-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Paradigms',
            },
        ),
        migrations.RemoveField(
            model_name='language',
            name='copntry',
        ),
        migrations.RemoveField(
            model_name='language',
            name='country',
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.ManyToManyField(to='languages.language')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(default=23092023, on_delete=django.db.models.deletion.CASCADE, to='languages.paradigm'),
            preserve_default=False,
        ),
    ]
