# Generated by Django 4.1 on 2022-09-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_paradigm_remove_language_copntry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.paradigm'),
        ),
    ]
